# Imagen base PHP con Apache
FROM php:8.2-apache

# Instalar extensiones necesarias
RUN docker-php-ext-install pdo pdo_mysql mysqli

# Copiar todo el proyecto al servidor
COPY . /var/www/html/

# Habilitar CORS
RUN a2enmod headers
RUN echo '<IfModule mod_headers.c>\n\
    Header set Access-Control-Allow-Origin "*"\n\
    Header set Access-Control-Allow-Methods "GET, POST, OPTIONS"\n\
    Header set Access-Control-Allow-Headers "Content-Type"\n\
</IfModule>' > /etc/apache2/conf-available/cors.conf \
&& a2enconf cors

EXPOSE 80
CMD ["apache2-foreground"]
